// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcchravmtcjavdmwkbhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjY2hyYXZtdGNqYXZkbXdrYmh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTA4NzgsImV4cCI6MjA3MTI2Njg3OH0.GOYK2hzUVeWDbjlXaCRaGN8xcQFqKw6ptSv91SPMgqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});